### PR TITLE
Use mb_strlen to support multibyte chars

### PR DESCRIPTION
**Pull request by simonschaufi**
This fixes an issue when you use multibyte characters as well in your table like:

```
+------------+
| Zip        |
+------------+
| 72336 X    |
| 78532 ✔    |
+------------+
```

The second fix is to use independent widths of each column (before they all had the same width)

### CODE REVIEW

**Comment by simonschaufi** [comment]
@miloske85 ping

**Comment by miloske85** [comment]
Sorry for the long wait, I missed those notifications before.

**Comment by simonschaufi** [comment]
@miloske85 thanks. could you also tag a new release please?

**Comment by simonschaufi** [comment]
@miloske85 thanks. could you also tag a new release please?

**Pull request merged**
